### ISSUE TITLE
Events use their end time as their start time

### ISSUE THREAD

**Issue by garthk** [honeycombio/honeycomb-lambda-extension#11]
You're using the time you get the log message as its timestamp, and I can't find a means to trust the event's timestamp or compensate with its duration:

```go
			ts, err := time.Parse(time.RFC3339, msg.Time)
			if err != nil {
				// Couldn't parse timestamp from AWS, so let libhoney default to time.Now()
				// and log this as lambda_extension.time
				event.AddField("lambda_extension.time", msg.Time)
			} else {
				event.Timestamp = ts
			}
```

When I send events to standard output with the [HoneycombConsoleSpanExporter](https://github.com/honeycombio/opentelemetry-exporter-python/blob/c25bad2be5c88e14311c37b84c5225943a21fce0/opentelemetry/ext/honeycomb/__init__.py#L86-L105), the result after capture by `honeycomb-lambda-extension` is that events with a duration appear to start when they ended:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/15906/104142084-0aa82880-540e-11eb-882a-0ef2d97b182a.png">

Strikes me a complete solution while minimising surprise for people consuming other Honeycomb adapters would be to:

* Trust `timestamp` in the JSON event if it's present (matching Honeytail) or, if not,

* Adjust `msg.Time` backwards by `duration_ms` in the JSON event if it's present (matching the Beelines)

Perhaps you could take environment variables to cater for the dataset's [definitions](https://docs.honeycomb.io/working-with-your-data/managing-your-data/definitions/) _eg._ `LIBHONEY_DATASET_SPAN_DURATION_FIELD`, though it's a mouthful. Uh, keyboardful.

**Comment by paulosman** [comment]
Thanks for the detailed issue @garthk. I agree with you that grabbing the timestamp from the event is the ideal approach, followed by doing a calculation based on the duration if present. Just letting you know that this is in progress now - I'll ping you once we have a PR ready.

**Comment by paulosman** [comment]
@garthk waiting on docs PR to merge, but in the meantime, here's your ARN: 

`arn:aws:lambda:us-east-1:702835727665:layer:honeycomb-lambda-extension:5`

(replace `us-east-1` with whatever region you're in).
