### ISSUE TITLE
Support publishing directly from Beelines

### ISSUE THREAD

**Issue by robwdux** [honeycombio/honeycomb-lambda-extension#19]
Lambda Extension should work out of box with Beelines as well as plain structured events. The extension only [supports structured event / manual tracing](https://github.com/honeycombio/honeycomb-lambda-extension/blob/main/logsapi/server.go#L45-L75) whereas the [honeycomb publisher for lambda](https://github.com/honeycombio/agentless-integrations-for-aws#honeycomb-publisher-for-lambda
) only supports data from beelines and not plain structured data or manual tracing.

If all beelines are consistent, then possibly the existence of `data.meta.beeline_version` would inform processing the Cloudwatch record as an event from a beeline.

https://honeycombpollinators.slack.com/archives/CJRF6BXF1/p1619145791058100 cc @jharley

**Comment by vreynolds** [comment]
@robwdux does #21 address the issue?
