### ISSUE TITLE
More insight into what the underlying libhoney client is doing?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/honeycomb-lambda-extension#23]
The libhoney client had its logger nerfed a while back. We've since added logging to the extension itself based on the value of a `HONEY_LOG_LEVEL` environment variable. The libhoney client could also log based on this to provide insight into what it is doing in moments where behavior need some debugging.

Along with this, consider a response handler that logs some information about libhoney.TxResponses when enabled.

**Comment by vreynolds** [comment]
closed via #38
