### ISSUE TITLE
Add more regions and make sure new regions are accessible

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-lambda-extension#91]
**Is your feature request related to a problem? Please describe.**

We added new regions to be published, but it turns out we needed an extra step to enable those regions in AWS console. Those are now enabled, so we need to ensure the extension is accessible as expected in those regions.

- [x] af-south-1 `"arn:aws:lambda:af-south-1:702835727665:layer:honeycomb-lambda-extension-x86_64:1"`
- [x] ap-east-1 `"arn:aws:lambda:ap-east-1:702835727665:layer:honeycomb-lambda-extension-x86_64:1"`
- [x] eu-south-1 `"arn:aws:lambda:eu-south-1:702835727665:layer:honeycomb-lambda-extension-x86_64:1"`
- [x] me-south-1 `"arn:aws:lambda:me-south-1:702835727665:layer:honeycomb-lambda-extension-x86_64:1"`

We've also uncovered a couple regions we weren't previously publishing in, so we should add those and confirm they are accessible as well.

- [x] ap-southeast-3 `"arn:aws:lambda:ap-southeast-3:702835727665:layer:honeycomb-lambda-extension-x86_64:1"`
- [x] ap-northeast-3 `"arn:aws:lambda:ap-northeast-3:702835727665:layer:honeycomb-lambda-extension-x86_64:2"`
- ~cn-northwest-1~
- ~cn-north-1~

**Comment by MikeGoldsmith** [comment]
New regions:
- [x] eu-south-1 - layer version 1
- [x] ap-southeast-3 - layer version 1
- [x] ap-northeast-3 - layer version 1
- [ ] cn-northwest-1 - can't get layer
- [ ] cn-north-1 - can't get layer

**Comment by JamieDanielson** [comment]
Looks like these regions in China are [only accessed and accessible with a special account](https://www.amazonaws.cn/en/about-aws/china/).

> Customers who wish to use Amazon Web Services resources in either Amazon Web Services China (Beijing) Region operated by Sinnet, or China (Ningxia) Region operated by NWCD, or both, are required to create an Amazon Web Services (China) Account, a set of credentials that are distinct and separate from other Amazon Web Services global Accounts. Only customers with an Amazon Web Services (China) Account will be able to use resources in China regions. 

So I think we should remove those regions from our list (or, not add them to our list anyway) until such time it becomes critical for us to have layers published and available there.
