### ISSUE TITLE
investigate failure mode during outage

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-lambda-extension#97]
If there is an outage, it seems the extension hangs on for the full timeout period with no ability to stop early if an error is received. Investigate this behavior and consider alternate behavior to potentially help mitigate issues in the future.

**Additional context**

[A thread in Pollinators Slack](https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1662710405668229) includes some discussion as this came up during an outage earlier in the month.

> Looking through the code there is a hardcoded http timeout of 60 seconds in underlying libhoney-go (https://github.com/honeycombio/libhoney-go/blob/main/transmission/transmission.go#L101) and then in the lambda extension there is no configurability of the http transport (https://github.com/honeycombio/honeycomb-lambda-extension/blob/main/main.go#L146) which means it would use the default transport which has a connection timeout of 30 seconds. So given the current code I think both of these scenarios would be possible culprits. Hoping for some additional insight.

**Comment by robbkidd** [comment]
part 1: [configurable send timeout in libhoney-go](https://github.com/honeycombio/libhoney-go/pull/190)
part 2: update libhoney-go to ☝🏻  and teach lambda log extension to configure send timeout ( #98 )
